### ISSUE TITLE
Object rotated in Blockbench appears inverted in-game

### ISSUE THREAD

**Issue by NitrolessWasTaken** [TheOneTrueZandra/Figura#11]
When rotating an object in Blockbench and trying to use it in-game, the object appears to have been rotated the opposite way.

![image](https://user-images.githubusercontent.com/81432274/112660265-89c9cc00-8e55-11eb-8135-8db83026e3ac.png)

![image](https://user-images.githubusercontent.com/81432274/112660662-f6dd6180-8e55-11eb-9c3e-bbe002a592e1.png)

Sorry if this isn't enough, never submitted an issue before.

**Comment by TheOneTrueZandra** [comment]
Fixed in 0.0.3 / [this commit](https://github.com/TheOneTrueZandra/Figura/commit/99912d2c9e000daba01c17048c6516af7f47d69b)

**Comment by NitrolessWasTaken** [comment]
Issue still persists

![image](https://user-images.githubusercontent.com/81432274/112724138-18038800-8f12-11eb-902c-7d306f584b5f.png)
![image](https://user-images.githubusercontent.com/81432274/112724190-66b12200-8f12-11eb-8676-800505ca753d.png)
(Note that they rotate along their pivot points, which are placed different)

![image](https://user-images.githubusercontent.com/81432274/112724196-73357a80-8f12-11eb-9d00-edc96a092b59.png)
Running 0.0.3

**Comment by NitrolessWasTaken** [comment]
@TheOneTrueZandra
Can you have another look?
(I'm not sure if you get notified of comments on closed issues, making sure you see this.)
